WIP: compile binary job
Co-authored-by: Kevin Yeap <kyeap@pivotal.io>
Co-authored-by: Larry Hamel <lhamel@pivotal.io>

diff --git a/ci/pipeline.yml b/ci/pipeline.yml
--- a/ci/pipeline.yml
+++ b/ci/pipeline.yml
@@ -2,6 +2,7 @@
 groups:
 - name: All
   jobs:
+  - build_binaries
   - GPDB4.3
   - GPDB5
   - GPDB5-oracle7
@@ -95,6 +96,7 @@ resources:
     start: 6:00 AM
     stop: 7:00 AM
 
+# TODO mark these as src with name change
 - name: gpbackup
   type: git
   source:
@@ -113,6 +115,13 @@ resources:
     branch: master
     private_key: {{gpbackup-ddboost-plugin-remote-key}}
     uri: {{gpbackup-ddboost-plugin-git-remote}}
+
+- name: gpbackup_manager_src
+  type: git
+  source:
+    branch: master
+    private_key: {{gp-backup-manager-remote-deploy-key}}
+    uri: {{gp-backup-manager-git-remote}}
 
 - name: gpbackup_tagged_src
   type: git
@@ -359,6 +368,105 @@ resources:
     regexp: gpbackup-osl-v(.*).txt
 
 jobs:
+- name: build_binaries
+  plan:
+  - aggregate:
+    - get: gpbackup
+      trigger: true
+    - get: gpbackup_s3_plugin
+    - get: gpbackup-dependencies
+    - get: gpbackup_manager_src
+    - get: nightly-trigger
+      trigger: true
+  - task: build-binaries
+    config:
+      platform: linux
+      inputs:
+        - name: gpbackup-dependencies
+        - name: gpbackup
+          path: go/src/github.com/greenplum-db/gpbackup
+        - name: gpbackup_s3_plugin
+          path: go/src/github.com/greenplum-db/gpbackup-s3-plugin
+        - name: gpbackup_manager_src
+          path: go/src/github.com/pivotal/gp-backup-manager
+      outputs:
+        - name: github_release_components
+      image_resource:
+        type: docker-image
+        source:
+          repository: golang
+          tag: '1.12.5'
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          set -ex
+          export GOPATH=$(pwd)/go
+          export PATH=$PATH:$GOPATH/bin
+
+          tar -zxf gpbackup-dependencies/dependencies.tar.gz -C $GOPATH/src/github.com/greenplum-db/gpbackup/
+
+          # Build gpbackup
+          pushd $GOPATH/src/github.com/greenplum-db/gpbackup
+            make depend
+
+            # NOTE: we are building binaries without a cluster installed, so distributing the backup_helper fails--continue anyway
+            CGO_ENABLED=0 make build || true
+            version=`git describe --tags | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/'`
+          popd
+          echo ${version} > gpbackup_version
+
+          # Build s3 plugin
+          pushd $GOPATH/src/github.com/greenplum-db/gpbackup-s3-plugin
+            make depend
+            CGO_ENABLED=0 make build
+            s3_plugin_version=`git describe --tags | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/'`
+          popd
+          echo ${s3_plugin_version} > s3_plugin_version
+
+          # todo handle ddboost in different container
+
+          # gpbackup-manager
+          pushd $GOPATH/src/github.com/pivotal/gp-backup-manager
+            make depend
+            CGO_ENABLED=0 make build
+          popd
+
+          # prepare github release; also, the bin_gpbackup.tar.gz file is used in the next build_gppkg task
+          pushd github_release_components
+            # Create install script
+            printf "#!/bin/sh\nset -x\ntar -xzvf bin_gpbackup.tar.gz -C \$GPHOME" > install_gpdb_component
+            chmod +x install_gpdb_component
+
+            # Create test script
+            cp ../gpbackup_version .
+            cp ../gpbackup_version version
+            cp ../s3_plugin_version .
+            cp $GOPATH/src/github.com/greenplum-db/gpbackup/ci/scripts/smoke_test_component_gpbackup.sh smoke_test_gpdb_component
+            # Assemble binaries
+            mkdir -p bin
+            cp $GOPATH/bin/gpbackup bin/
+            cp $GOPATH/bin/gpbackup_helper bin/
+            cp $GOPATH/bin/gprestore bin/
+            cp $GOPATH/bin/gpbackup_s3_plugin bin/
+            cp $GOPATH/bin/gpbackup_manager bin/
+
+            # Test package
+            export PATH=$PATH:`pwd`/bin
+            # TODO reenable this
+            # ./smoke_test_gpdb_component
+
+            tar -czvf bin_gpbackup.tar.gz bin/
+
+            tar -czvf "gpbackup-${version}.tar.gz" bin_gpbackup.tar.gz install_gpdb_component smoke_test_gpdb_component gpbackup_version version s3_plugin_version
+          popd
+
+  - put: github_release_components
+    params:
+      file: github_release_components/gpbackup-*.tar.gz
+
+
 - name: build_dependencies
   plan:
   - aggregate:
